#!/usr/bin/env sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
	echo "Create symlinks for the dotfiles in this repository.
	-f	Remove existing destination files
	-i	Prompt whether to remove destinations"
	exit 0
fi

script_file="$(realpath --canonicalize-existing --logical "$0")"
if [ ! -f "$script_file" ]; then
	echo "'script_file' does not exist: $script_file" >&2
	exit 1
fi

script_dir="$(dirname "$script_file")"
arg="$1"
dotfile_link() {
	if [ "$arg" = "" ]; then
		ln -s -T "$(realpath "$script_dir/$2")" "$HOME/$1"
	else
		ln "$arg" -s -T "$(realpath "$script_dir/$2")" "$HOME/$1"
	fi
}

dotfile_link	.bash_profile 				bash/bash_profile
dotfile_link	.bashrc 				bash/bashrc
dotfile_link	.config/bat/config			batconfig
dotfile_link	.config/ghostty/config 			ghosttyconfig
dotfile_link	.config/nvim 				nvim
dotfile_link	.config/ripgrep/ripgreprc 		ripgreprc
dotfile_link	.config/xdg-terminals.list 		xdg-terminals.list
dotfile_link	.gitconfig 				gitconfig
dotfile_link	.local/bin/fullup 			bin/fullup
dotfile_link	.local/bin/gnome-toggle-style		bin/gnome-toggle-style
dotfile_link	.local/bin/witcher3modmanager		bin/witcher3modmanager
dotfile_link	.local/bin/witcher3scriptmerger		bin/witcher3scriptmerger
dotfile_link	.ssh/config 				sshconfig
dotfile_link	.zshrc 					zshrc
