#!/usr/bin/zsh

print_upgrade() {
	fmt "Upgrading $1"
}

fmt() {
	bold=$(tput bold)
	reset=$(tput sgr0)
	blue=$(tput setaf 4)
	printf "\n%s%s::%s%s %s%s...\n" "$bold" "$blue" "$reset" "$bold" "$1" "$reset"
}

paru
print_upgrade "neovim"
bob update --all
print_upgrade "flatpak"
flatpak update
flatpak remove --unused
print_upgrade "zinit and plugins"
source ~/.local/share/zinit/zinit.git/zinit.zsh
zinit self-update
zinit update
print_upgrade "rust"
rustup update
fmt "Fetching dotfile changes"
git -C "${HOME}/.dotfiles" fetch -p


