# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export EDITOR=nvim
export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"

alias te="\$EDITOR"
alias vim="nvim --noplugin"

export PATH="$PATH:$HOME/.bin:$HOME/.local/.bin:$HOME/.cargo/bin:$HOME/.go/bin:$HOME/.local/share/npm/bin"
export npm_config_prefix="$HOME/.local/share/npm"
