# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Environment Variables
export PATH="$HOME/.local/bin/:$HOME/.cargo/bin:$HOME/.local/share/npm/bin:$PATH"
export PATH="$HOME/.local/share/bob/nvim-bin:$PATH"
[[ ! -v EDITOR ]] && export EDITOR='nvim'
export npm_config_prefix="$HOME/.local/share/npm"
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/ripgrep/ripgreprc"

# History (see `man bash`)
export HISTCONTROL="ignoreboth:erasedups"
export HISTSIZE=5000
export HISTFILESIZE=5000
shopt -s histappend

# Set vim mode
if [[ $EDITOR == "nvim" || $EDITOR == "vim" || $EDITOR == "vi" ]]; then
	set -o vi
fi

# Aliases
alias ls='ls --color'
alias tree='tree -C'
alias te="$EDITOR"
alias vim="nvim --noplugin"
alias diffed='$EDITOR $(git diff --name-only --relative)'
alias pacdiff='DIFFPROG="nvim -d" pacdiff -b -3 -s'
